# Generated by Django 4.2.11 on 2024-04-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='username',
        ),
    ]
