# Generated by Django 4.2.11 on 2024-05-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxs', '0005_mymsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyConsult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=9999)),
            ],
        ),
    ]
