# Generated by Django 4.2.11 on 2024-05-23 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxs', '0006_myconsult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myconsult',
            old_name='content',
            new_name='contentlist',
        ),
    ]
