# Generated by Django 4.2.11 on 2024-06-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxs', '0007_rename_content_myconsult_contentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('unit', models.CharField(max_length=128)),
                ('area', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='boss',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='unit',
            field=models.CharField(default=11, max_length=128),
            preserve_default=False,
        ),
    ]
