# Generated by Django 4.2.11 on 2024-06-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxs', '0008_adminuserinfo_userinfo_address_userinfo_boss_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyConsultMsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultID', models.IntegerField()),
                ('type', models.IntegerField()),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
